server:
  port: 8087

spring:
  application:
    name: reporting-and-analytics-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/analytics_db;MODE=PostgreSQL;AUTO_SERVER=TRUE}
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

